# site settings
title: Form Tools Documentation
email: ben.keen@gmail.com
description: "Documentation and tutorials for all things Form Tools."
baseurl: "http://localhost:8888/formtools-site/docs.formtools.org"
url: "http://docs.formtools.org"
resourceurl: "http://localhost:8888/formtools-site/formtools.org"

# build settings
markdown: kramdown
permalink: pretty
showWrapper: true
